#!/usr/bin/env python3
"""
Oura Data Analysis Script

Analyzes Oura Ring data using Claude AI to provide insights on sleep,
recovery, and activity patterns with actionable recommendations.

Requires:
- ANTHROPIC_API_KEY environment variable
- oura-data.json file (generated by sync_oura.py)
"""

import json
import os
import sys
from datetime import datetime, timezone

try:
    import anthropic
except ImportError:
    anthropic = None


def load_oura_data():
    """Load Oura data from JSON file."""
    try:
        with open("oura-data.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print("oura-data.json not found. Run sync_oura.py first.", file=sys.stderr)
        return None
    except json.JSONDecodeError as e:
        print(f"Error parsing oura-data.json: {e}", file=sys.stderr)
        return None


def prepare_data_summary(data):
    """Prepare a summary of Oura data for Claude analysis."""
    days = data.get("days", [])
    workouts = data.get("workouts", [])

    if not days:
        return None

    # Get last 14 days for detailed analysis
    recent_days = days[:14]

    # Calculate statistics
    def avg(values):
        valid = [v for v in values if v is not None]
        return round(sum(valid) / len(valid), 1) if valid else None

    def get_values(key):
        return [d.get(key) for d in recent_days]

    stats = {
        "days_analyzed": len(recent_days),
        "date_range": f"{recent_days[-1]['date']} to {recent_days[0]['date']}",
        "sleep": {
            "avg_score": avg(get_values("sleep_score")),
            "avg_hours": avg([d.get("total_sleep_seconds", 0) / 3600 if d.get("total_sleep_seconds") else None for d in recent_days]),
            "avg_deep_hours": avg([d.get("deep_sleep_seconds", 0) / 3600 if d.get("deep_sleep_seconds") else None for d in recent_days]),
            "avg_rem_hours": avg([d.get("rem_sleep_seconds", 0) / 3600 if d.get("rem_sleep_seconds") else None for d in recent_days]),
            "avg_efficiency": avg(get_values("sleep_efficiency")),
            "scores": get_values("sleep_score"),
        },
        "readiness": {
            "avg_score": avg(get_values("readiness_score")),
            "scores": get_values("readiness_score"),
        },
        "activity": {
            "avg_score": avg(get_values("activity_score")),
            "avg_steps": avg(get_values("steps")),
            "avg_calories": avg(get_values("active_calories")),
            "scores": get_values("activity_score"),
        },
        "heart": {
            "avg_hrv": avg(get_values("average_hrv")),
            "avg_resting_hr": avg([d.get("lowest_hr") or d.get("resting_hr") for d in recent_days]),
            "hrv_values": get_values("average_hrv"),
        },
        "recovery": {
            "avg_temp_deviation": avg(get_values("temperature_deviation")),
            "avg_breath_rate": avg(get_values("average_breath")),
        },
        "workouts_count": len([w for w in workouts if w.get("date", "") >= recent_days[-1]["date"]]),
    }

    # Build daily breakdown for context
    daily_breakdown = []
    for d in recent_days[:7]:  # Last 7 days detailed
        daily_breakdown.append({
            "date": d.get("date"),
            "sleep_score": d.get("sleep_score"),
            "sleep_hours": round(d.get("total_sleep_seconds", 0) / 3600, 1) if d.get("total_sleep_seconds") else None,
            "deep_sleep_hours": round(d.get("deep_sleep_seconds", 0) / 3600, 1) if d.get("deep_sleep_seconds") else None,
            "readiness_score": d.get("readiness_score"),
            "activity_score": d.get("activity_score"),
            "steps": d.get("steps"),
            "hrv": d.get("average_hrv"),
            "resting_hr": d.get("lowest_hr") or d.get("resting_hr"),
            "temp_deviation": d.get("temperature_deviation"),
        })

    return {
        "stats": stats,
        "daily_breakdown": daily_breakdown,
    }


def analyze_with_claude(summary):
    """Use Claude to analyze the Oura data and provide insights."""
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        print("Missing ANTHROPIC_API_KEY", file=sys.stderr)
        return None

    if anthropic is None:
        print("anthropic package not installed", file=sys.stderr)
        return None

    stats = summary["stats"]
    daily = summary["daily_breakdown"]

    daily_text = "\n".join([
        f"  {d['date']}: Sleep {d['sleep_score']}/100 ({d['sleep_hours']}h, {d['deep_sleep_hours']}h deep), "
        f"Readiness {d['readiness_score']}, Activity {d['activity_score']}, "
        f"Steps {d['steps']}, HRV {d['hrv']}, RHR {d['resting_hr']}"
        for d in daily
    ])

    prompt = f"""Analyze this Oura Ring health data and provide personalized insights. The user has POTS (Postural Orthostatic Tachycardia Syndrome), so consider how sleep, HRV, and recovery metrics are especially important for managing their condition.

DATA SUMMARY ({stats['days_analyzed']} days: {stats['date_range']}):

SLEEP:
- Average Score: {stats['sleep']['avg_score']}/100
- Average Duration: {stats['sleep']['avg_hours']} hours
- Average Deep Sleep: {stats['sleep']['avg_deep_hours']} hours
- Average REM Sleep: {stats['sleep']['avg_rem_hours']} hours
- Average Efficiency: {stats['sleep']['avg_efficiency']}%

READINESS:
- Average Score: {stats['readiness']['avg_score']}/100

ACTIVITY:
- Average Score: {stats['activity']['avg_score']}/100
- Average Steps: {stats['activity']['avg_steps']}
- Average Active Calories: {stats['activity']['avg_calories']}
- Workouts in period: {stats['workouts_count']}

HEART & RECOVERY:
- Average HRV: {stats['heart']['avg_hrv']} ms
- Average Resting HR: {stats['heart']['avg_resting_hr']} bpm
- Average Temp Deviation: {stats['recovery']['avg_temp_deviation']}°C
- Average Breathing Rate: {stats['recovery']['avg_breath_rate']}/min

DAILY BREAKDOWN (last 7 days):
{daily_text}

Based on this data, provide analysis in the following format. Be specific and reference actual numbers from the data. Consider POTS-specific factors like the importance of consistent sleep for autonomic function, HRV as an indicator of nervous system health, and the balance between activity and recovery.

Return ONLY valid JSON in this exact format:
{{
  "overall_assessment": "A 2-3 sentence overall assessment of their health metrics this period",
  "whats_going_well": [
    "Specific positive observation 1 with data reference",
    "Specific positive observation 2 with data reference",
    "Specific positive observation 3 with data reference"
  ],
  "areas_to_improve": [
    "Specific area needing attention 1 with actionable advice",
    "Specific area needing attention 2 with actionable advice",
    "Specific area needing attention 3 with actionable advice"
  ],
  "pots_specific_insights": "1-2 sentences about what the data suggests for POTS management specifically",
  "focus_for_next_week": "One specific, actionable thing to focus on this coming week"
}}"""

    try:
        client = anthropic.Anthropic(api_key=api_key)

        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )

        response_text = message.content[0].text.strip()

        # Try to extract JSON if wrapped in markdown
        if "```json" in response_text:
            response_text = response_text.split("```json")[1].split("```")[0].strip()
        elif "```" in response_text:
            response_text = response_text.split("```")[1].split("```")[0].strip()

        return json.loads(response_text)

    except json.JSONDecodeError as e:
        print(f"Failed to parse Claude response as JSON: {e}", file=sys.stderr)
        print(f"Response was: {response_text[:500]}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"Error calling Claude API: {e}", file=sys.stderr)
        return None


def main():
    # Load Oura data
    data = load_oura_data()
    if not data:
        # Create empty report
        report = {
            "updated": datetime.now(timezone.utc).isoformat(),
            "error": "No Oura data available. Run sync_oura.py first.",
            "analysis": None,
        }
        with open("oura-analysis.json", "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)
            f.write("\n")
        return

    # Prepare summary
    summary = prepare_data_summary(data)
    if not summary:
        print("No data to analyze", file=sys.stderr)
        return

    print(f"Analyzing {summary['stats']['days_analyzed']} days of Oura data...")
    print(f"  Sleep avg: {summary['stats']['sleep']['avg_score']}")
    print(f"  Readiness avg: {summary['stats']['readiness']['avg_score']}")
    print(f"  HRV avg: {summary['stats']['heart']['avg_hrv']}")

    # Analyze with Claude
    analysis = analyze_with_claude(summary)

    # Create report
    report = {
        "updated": datetime.now(timezone.utc).isoformat(),
        "data_range": summary["stats"]["date_range"],
        "days_analyzed": summary["stats"]["days_analyzed"],
        "summary_stats": summary["stats"],
        "analysis": analysis,
    }

    # Write report
    with open("oura-analysis.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
        f.write("\n")

    if analysis:
        print("\nAnalysis complete!")
        print(f"  Overall: {analysis.get('overall_assessment', 'N/A')[:100]}...")
        print(f"  Going well: {len(analysis.get('whats_going_well', []))} points")
        print(f"  To improve: {len(analysis.get('areas_to_improve', []))} points")
    else:
        print("\nAnalysis failed - check ANTHROPIC_API_KEY")


if __name__ == "__main__":
    main()
